<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QZ-LT-199" failures="23" tests="169" name="executionClasses.FormTest" time="1931.113" errors="0" timestamp="2024-12-27T16:49:04 IST" skipped="0">
  <testcase classname="executionClasses.FormTest" name="test" time="11.337"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.211"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.808"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.076"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.898"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.963"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.134"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.588"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.146"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.486"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.890"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.690"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.991"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.495"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.432"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.789">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.427">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.010"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.774"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.730"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.624"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.250"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.003">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.093"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.023"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.444">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.472"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.264"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.108"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.108"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.412"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.430"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.764"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.687"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.837"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.119"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.121"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.554"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.847"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.196"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.114"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.243"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.453"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.083">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.808">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.902"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.084"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.675"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.259"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.126"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.872"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.534"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.024"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.931"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.559"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.914"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.252"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.614"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.340"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.696"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.864"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.813"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.940"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.686"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.667"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.683"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.825"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.355"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.483"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.326">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.036"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.611"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="13.529"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.173"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="13.060"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.182"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.331"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.696"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.612">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.002"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.208"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.837"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.496"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.933"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.793">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.226"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.182"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.767"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.366"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.409"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.492"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.602">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.345">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.347"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.200"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.720"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.305"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.747"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.264">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.950"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.040"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.604"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.063"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.111">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.223"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.832"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.571"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.163"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.796">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.500"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.949"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.840"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.610"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.885"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.354">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.695"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.438"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.380"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.341"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.502"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.782">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.332"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.293">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.940">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.973">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.638"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.672"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.392"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.655"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.148">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.923"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.053"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.463"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.856"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.589"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.482"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.577"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.019"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.391"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.426"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.759">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.992"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.382">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.290"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="13.171"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.194"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.889"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.134"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.173"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.891"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.383"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.916"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.617"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.392"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.269"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.511"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="10.956"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.453">
    <failure message="mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: mobile number is Mandatory expected [rgb(40, 167, 69)] but found [rgb(220, 53, 69)]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at utils.TestNGHelpers.validateUsingAsserts(TestNGHelpers.java:36)
at executionClasses.FormTest.test(FormTest.java:42)
at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.212"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.464"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="13.863"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.322"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.520"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.359"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.713"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.126"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.366"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="12.316"/>
  <system-out/>
  <testcase classname="executionClasses.FormTest" name="test" time="11.202"/>
  <system-out/>
</testsuite> <!-- executionClasses.FormTest -->
